### ISSUE TITLE
Page is not responsive. Some part of the page appears outside the screen

### ISSUE THREAD

**Issue by Reeya123** [FDA-ARGOS2/argosdb#13]

**Comment by Reeya123** [comment]
Hi Robel, I am taking a look at the code and will try to solve the two issues by myself. But if I am not able to figure it out by tomorrow, could I pass this task off to you?

**Comment by steph-sing** [comment]
@Reeya123 is it ready for Robel?

**Comment by Reeya123** [comment]
Hi. I have figured out one issue(contact button) but couldn't solve this one. So have contacted Hadley to look into it. I apologize for the delay  but I assure you that this is a priority task on my list. I will update you one its done.

**Comment by Reeya123** [comment]
@steph-sing Hi Stephanie. The webpage is complete. Will push it now.

**Comment by steph-sing** [comment]
Please include ticket #14 in your edits before you push. please also update the status of all tickets assigned to you.

**Comment by steph-sing** [comment]
@Reeya123 can you please link your pull request to this ticket?
