### ISSUE TITLE
Update the site link for Argos webpage in the Readme

### ISSUE THREAD

**Issue by Reeya123** [FDA-ARGOS2/argosdb#19]
Updated code has been pushed in Argos DB repo. 
https://argosdb.org/
This link  directs to the old page. Kindly update above link in the Readme section.

**Comment by HadleyKing** [comment]
@Reeya123 I think you misunderstood what I asked you to do. 
This is not a task for Robel.
I was asking YOU to update the [README](https://github.com/FDA-ARGOS/argosdb/blob/main/README.md) for this repository explaining how people can make contributions or fixes to the webpage. 
For example: 
```
1) Pull this repository to a local environment
2) make sure the following required packages/programs are installed {List them}
3) Any other steps
4) Maybe also explain how to test before making a PR. 
```
The current README talks about using the Hugo framework but since we have switched to another process we should list that. 
Thanks,

**Comment by Reeya123** [comment]
@HadleyKing Hello Hadley. I understand this is a misunderstanding. This task wasn't about writing the steps in Read me. I'm aware that its my task. The only issue was
https://argosdb.org/    This particular link directs to the old page. I don't know how to make it direct to the new updated web page for everyone to access it without having to download and run the code on their local machine. Updating this link to direct it to the updated page for me is one task and updating the Readme with steps to make changes in the webpage is another task. Kindly guide me how to change just that particular link. Or I would appreciate if you direct me to any resources that contains instructions on how to do it. I will take care of the Readme steps

**Comment by Reeya123** [comment]
@HadleyKing Hello Hadley. I have updated the Readme. Kindly take a look and let me know of any changes. There's one issue in which I need your guidance. https://argosdb.org/  I tried creating a  link for the page such as this one on Github so team an access the page without having to download and run it on their local machine.  I did this by going in settings> Pages (on left side), I am unable to make the link. Its giving an error. You can view the issue by going to Actions besides Issues option on the page.
