### ISSUE TITLE
Push the new ARGOS DB webpage code to production.

### ISSUE THREAD

**Issue by Reeya123** [FDA-ARGOS2/argosdb#20]
https://argosdb.org/ -This link shows the old website. New changes have been made and pushed to the main branch. Kindly Update the link

**Comment by Reeya123** [comment]
@rajamazumder

**Comment by rykahsay** [comment]
@Reeya123 @kee007ney @rajamazumder  --- I have updated the code for the repo. Anyone should be able to EDIT contents of the pages and deploy changes in any of the argosdb servers (dev/test/beta/prd) following the instructions given in the README.md at the root of the repo.

**Comment by Reeya123** [comment]
Hello @rykahsay @HadleyKing . I am unable to follow the steps correctly in order to push my updated code to production. After making changes in the code, I ran the command python3 start.container.py as instructed in the readme. 

Error: PS C:\Users\gupta\OneDrive\Desktop\argosdb-main\app> python3 start_app_container.py
The syntax of the command is incorrect.

> app@0.1.0 build
> react-scripts build

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

I am assuming this is because it thinks that react script isn't in the node modules but I see it in the package.json file. I don't understand where I am going wrong.

 Also after running the above part,  exactly where would I make the changes that are asked in the below statement? 
-->To serve the APP at a given public domain name such as [www.argosdb.org](http://www.argosdb.org/), add the following lines to your apache VirtualHost directive (assuming the "app_port" you have selected in the conf/config.json configuration to be 5090)

**Comment by HadleyKing** [comment]
@Reeya123 
I have reassigned this issue to @kee007ney. The instructions in the `README.md` need to be followed on the ARGOS server. I do not believe you have access.

**Comment by steph-sing** [comment]
@HadleyKing do you have permission to do this? I don't think that I do
@kee007ney are you able to push this today?

**Comment by kee007ney** [comment]
@steph-sing Robel asked Dacian to give me permissions on the server to do it. Just sent a follow up now to ask for an ETA. Whenever I get permissions I'll push.

**Comment by steph-sing** [comment]
Thank you for the update Jonathon

**Comment by kee007ney** [comment]
@Reeya123 New version was pushed. Header portion is removed, but spacing still looks wrong. I'm guessing this is not what you want to see. @HadleyKing will look at the React framework to see if it's an issue here.

**Comment by kee007ney** [comment]
Hadley, Pat, and I talked this over. Hadley figured out that the HTML was duplicated in `/home/keeneyjg/argosdb/app/src/components/home_page.jsx`. When we remove that, it works fine. @Reeya123, I don't know if you added that content to that page or not.

Closing this as complete.

**Comment by steph-sing** [comment]
just checked and looks to be fixed. Thanks guys!
