### ISSUE TITLE
ArgosDB initial high-level data workflow

### ISSUE THREAD

**Issue by rajamazumder** [FDA-ARGOS2/argosdb#4]
[Argos_data_workflow.pptx](https://github.com/FDA-ARGOS2/argosdb/files/7205209/Argos_data_workflow.pptx)

**Comment by rajamazumder** [comment]
Live document for you to edit
https://docs.google.com/presentation/d/1dQcbQPZYSqFb9rgwGg8BQCCF2ScHxHvoThkrAbHqdJI/edit#slide=id.p

**Comment by rajamazumder** [comment]
@steph-sing can I close this?

**Comment by steph-sing** [comment]
yes! I need to run through all open tickets and close them because they don't close when 'done' automatically.
